spring:
  datasource:
    url: jdbc:mariadb://localhost:3316/sechong?useUnicode=true&characterEncoding=utf8mb4&serverTimezone=Asia/Seoul
    driver-class-name: org.mariadb.jdbc.Driver
    username: sechong
    password: sechong1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  data:
    redis:
      host: localhost
      port: 6380
      password: sequence
      timeout: 3s

server:
  port: 8080