server:
  port: 8080

spring:
  datasource:
    # 로컬(호스트)에서 스프링 실행 + 도커 mariadb 포트포워딩(3313) 사용하는 경우
    url: jdbc:mariadb://localhost:3313/sechong?useUnicode=true&characterEncoding=utf8mb4&serverTimezone=Asia/Seoul
    driver-class-name: org.mariadb.jdbc.Driver
    username: sechong
    password: sechong1234

  jpa:
    hibernate:
      ddl-auto: update          # 개발 단계: update, 운영 전환 시 validate 권장
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: Asia/Seoul
    open-in-view: false

  jackson:
    time-zone: Asia/Seoul

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: e7bda790984d6fc10f430435e270d709     # 실제 값
            client-secret: this-is-client-secret-key         # 실제 값
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"  # 카카오 콘솔에도 동일 등록
            scope: profile_nickname
            client-name: Kakao
            provider: kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  # ─────────────────────────────────────────────────────────────
  # Rediss
  # data:
  #   redis:
  #     host: localhost
  #     port: 6380
  #     password: sequence
  #     timeout: 3s
  #
  # 세션을 Redis에 보관하려면(선택):
  # session:
  #   store-type: redis
  # ─────────────────────────────────────────────────────────────

logging:
  level:
    org.hibernate.SQL: info
    org.springframework.security: info
